# ssh-proxy service configuration

server:
  # true to start each connection in a new process
  forking: false

  # true to parse proxy protocol to get the real client IP and port
  # set to false when proxy protocol is not used
  proxyProtocol: true

  # true to show provision info when starting a shell
  showProvisionInfo: true

# ssh proxy configuration
ssh:
  port: 2022
  serverKey: ${SECRET_FILES}/server_key

# Identity service configuration
identity:
  baseURL: http://${IDENTITY_SERVICE_HOST}:9090
  APIKey: !file ${SECRET_FILES}/identity_key
  timeout: 1000 

provisioner:
  baseURL: http://${PROVISIONER_SERVICE_HOST}:9201
  APIKey: !file ${SECRET_FILES}/provisioner_key
  timeout: 30000

nats:
  host: ${NATS_HOST}
  port: 4222
  token: !file ${SECRET_FILES}/nats_token

  sshFailures:
    enabled: true
    subject: ssh.failures
    publicIPOnly: true
    whitelist:
      - 147.32.0.0/0
