# ssh-proxy service configuration

server:
  # true to start each connection in a new process
  forking: false

  # true to parse proxy protocol to get the real client IP and port
  # set to false when proxy protocol is not used
  proxyProtocol: true

  # options for the provision info writer
  writerOptions:
    showProvisionInfo: false
    showPulse: true
    showPercentage: true
    showErrors: true
    showSystemErrors: false

  # SSH handshake timeout in seconds
  SSHHandshakeTimeout: 15

  # maximum number of direct TCP/IP connections allowed (per ssh connection)
  maxDirectTCPIPConnections: 15

  # sftp binary path in the workspace
  sftpBinary: /usr/local/bin/sftp

# ssh proxy configuration
ssh:
  port: 2022
  serverKey: ${SECRET_FILES}/server_key

session:
  address: session:9010
  tokenFilePath: /var/run/secrets/k8shell.io/session

identity:
  address: identity:9020
  tokenFilePath: /var/run/secrets/k8shell.io/identity

provisioner:
  address: provisioner:9030
  tokenFilePath: /var/run/secrets/k8shell.io/provisioner

k8shelld:
  tokenFilePath: /var/run/secrets/k8shell.io/k8shelld

nats:
  host: ${NATS_HOST}
  port: 4222
  user: sshproxy
  password: !file ${SECRET_FILES}/sshproxy_nats_token

  sshFailures:
    enabled: true
    subject: ssh.failures
    publicIPOnly: true
    whitelist:
      - 147.32.0.0/0
